[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

#[colors.vi_mode_cursor]
#text = "CellBackground"
#cursor = "CellForeground"
#
#[colors.selection]
#text = "CellForeground"
#background = "#44475a"

[colors.normal]
black = "#282c34"
red = "#ef596f"
green = "#89ca78"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#d55fde"
cyan = "#2bbac5"
white = "#abb2bf"

[colors.bright]
black = "#6a7895"
red = "#ef596f"
green = "#89ca78"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#d55fde"
cyan = "#2bbac5"
white = "#abb2bf"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "semibold" }
size = 13.5

[window]
padding = { x = 16, y = 16 }

[env]
TERM = "xterm-256color"
