#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$({
		for dir in $(fdfind . ~/Dev -E testing -E learning -d 1 -t d); do
			printf "%s\t%s\n" "$(basename "$dir")" "$dir"
		done
		for dir in $(fdfind . ~/Dev/testing -d 1 -t d); do
			printf "%s\t%s\n" "testing/$(basename "$dir")" "$dir"
		done
		for dir in $(fdfind . ~/Dev/learning --full-path -d 1 -t d); do
			printf "%s\t%s\n" "learning/$(basename "$dir")" "$dir"
		done
		printf "%s\t%s\n" "dot-files" "$HOME/dot-files"
	} | fzf --tac --delimiter $'\t' --with-nth 1 --prompt 'Project > ' | cut -f2)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
	if [[ "$selected" == *\/comhairle ]]; then
		tmux new-session -d -s $selected_name -c "$selected/ui" -n "UI"
		tmux send-keys -t $selected_name "nvim" C-m

		tmux new-window -t $selected_name -c "$selected/api" -n "API"
		tmux send-keys -t $selected_name "nvim" C-m

		tmux new-window -t $selected_name -c $selected -n "Runner"
		tmux send-keys -t $selected_name "cd ui/packages && pn comhairle" C-m
		tmux split-window -h -c $selected -t $selected_name
		tmux send-keys -t $selected_name "nix develop -c just api-dev" C-m
		tmux split-window -v -c $selected -t $selected_name
		tmux send-keys -t $selected_name "nix develop -c just pg" C-m

		tmux new-window -t $selected_name -c $selected -n "CLI"
		tmux select-window -t "$selected_name:UI"
	else
		tmux new-session -d -s $selected_name -c $selected -n "Editor"
		tmux send-keys -t $selected_name "nvim" C-m

		tmux new-window -t $selected_name -c $selected -n "Runner"
		tmux new-window -t $selected_name -c $selected -n "CLI"
		tmux select-window -t "$selected_name:Editor"
	fi
fi

if [[ ! -z $TMUX ]]; then
  tmux switch-client -t $selected_name
else
  tmux attach -t $selected_name
fi
