#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$({ fdfind . ~/Dev --full-path -E testing -d 1 -t d ; fdfind . ~/Dev/testing --full-path -d 1 -t d ; echo ~/dot-files ; } | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
	tmux new-session -d -s $selected_name -c $selected -n "Editor"
	tmux send-keys -t $selected_name "nvim" C-m

	tmux new-window -t $selected_name -c $selected -n "Runner"
	tmux new-window -t $selected_name -c $selected -n "CLI"
	tmux select-window -t "Editor"
fi

if [[ ! -z $TMUX ]]; then
  tmux switch-client -t $selected_name
else
  tmux attach -t $selected_name
fi
