#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$({ fdfind . ~/Dev --full-path -E testing -d 1 -t d ; fdfind . ~/Dev/testing --full-path -d 1 -t d ; echo ~/dot-files ; } | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected -d "nvim"\; attach
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ ! -z $TMUX ]]; then
  tmux switch-client -t $selected_name
else
  tmux attach -t $selected_name
fi
