require("config.lazy")
require("config.treesitter")
require("config.remap")
require("config.telescope")
require("config.oil")
require("config.barbar")
require("config.theme")
require("config.highlight-groups")
