local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find file" })
vim.keymap.set("n", "<leader>fw", builtin.live_grep, { desc = "Find word" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Search open buffers" })
vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Search git files" })
vim.keymap.set("n", "<leader>;", builtin.resume, { desc = "Open last search" })
